 const RENDER_PAGE_KEYS = {
    // user
    userLogin: "user/login",
    userSignup: "user/signup",
    userOtp: "user/otp",
    userHome: "user/home",
    userLanding: "user/landing",
    userPage404: "user/page-404",
    userShop: "user/shop",
    userAbout: "user/about",
    userForgotPassword: "user/forgotpassword",
    userOtpForgotPass: "user/otpforgotpass",
    userNewPassword: "user/newpassword",
    userProfile: "user/userProfile",
    userEditProfile: "user/editProfile",
    userAddress: "user/useraddress",
    userWallet: "user/wallet",
    userWishlist: "user/wishlist",
    userCart: "user/cart",
    userCheckout: "user/checkout",
    userOrderConfirmation: "user/OrderConfirmation",
    userRazorpaySuccess: "user/razorpay-successpage",
    userProductDetails: "user/product-details",
    userOrders: "user/userorders",
    userError: "user/error",

    //   admin
    adminLogin: "admin/login",
    adminDashboard: "admin/dashboard",
    adminOrderManage: "admin/ordermanage",
    adminProductAdd: "admin/product-add",
    adminProducts: "admin/products",
    adminEditProduct: "admin/editproduct",
    adminOffer: "admin/offer",
    adminSalesReports: "admin/sales-reports",
    adminPageError: "admin/pageError",
    adminPage404: "admin/page-404",
    adminSalesChart: "admin/saleschart",
    adminCategory: "admin/category",
    adminEditCategory: "admin/edit-category",
    adminBrand: "admin/Brand",
    adminCoupons: "admin/coupons",
    adminCoustomers: "admin/coustomers",
   
};
module.exports = {RENDER_PAGE_KEYS};