name: Deploy to EC2

on:
  push:
    branches:
      - main  # replace 'main' if your working branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/shoe-vault  # replace with your project folder path in EC2
          git pull origin main        # pull latest code from your branch
          # If you use PM2 or any process manager to run your server, restart it here, e.g.:
          # pm2 restart app
